### PR TITLE
feat: support for 'create' event from the inotify watcher

### PR DESCRIPTION
**Pull request by neelayu**
Inotify watcher type will now emit "CREATE" file event when the watcher is defined on the parent directory.

PS: It also shows commit from the Previous unmerged PR

### CODE REVIEW

**Comment by neelayu** [comment]
@powersj Can you go through this PR?

**Review by powersj — COMMENTED** [review]
Here is my hesitation: this fork has not been updated in years and I'm not sure what to think about the change in behavior. I think it looks good in general, @srebhan thoughts?

**Comment by neelayu** [comment]
Makes sense. Lets build a consensus on this and then we can proceed.

**Review by srebhan — APPROVED** [review]
Looks good to me. However, as @powersj said, it might make sense to completely switch the underlying library in Telegraf, e.g. to https://github.com/fsnotify/fsnotify...

**Comment by neelayu** [comment]
@srebhan that's a reasonable ask. but could involve a lot of work since this repo also uses `fsnotify` for `inotify` watch type. `poll` is not supported by `fsnotify` so might have to think about other alternatives

**Comment by srebhan** [comment]
I agree but I would also welcome effort in that direction. https://pkg.go.dev/github.com/docker/docker/pkg/filenotify is a wrapper around `fsnotify` with support for polling. Didn't test that yet nor looked too deep into it. Maybe you can take a look?

**Comment by neelayu** [comment]
Hey @srebhan I looked at the above pkg and it seems they have removed in from the source. Although, we can still import it, but there is no active maintenance. Can we proceed with the current state?

**Comment by srebhan** [comment]
@neelayu what a pitty. This is the last point of existance: https://github.com/moby/moby/tree/2a9e6ace706999be3c0d36f1f94ce20cc3ad33b5/pkg/filenotify

**Comment by redbaron** [comment]
Another more maintained candidate is https://pkg.go.dev/kubesphere.io/fluentbit-operator/pkg/filenotify

**Review by powersj — APPROVED** [review]

**Pull request merged**
